### ISSUE TITLE
Tìm hiểu về DynamoDB

### ISSUE THREAD

**Issue by nguyentuanphi1609** [nguyentuanphi1609/Project_CloudComputing#1]
Tìm hiểu về DynamoDB sử dụng dịch vụ serverless của AWS

**Comment by myle2000** [comment]
[DynamoDB.docx](https://github.com/nguyentuanphi1609/Project_CloudComputing/files/6377228/DynamoDB.docx)

**Comment by myle2000** [comment]
[DynamoDB-đã chuyển đổi.pdf](https://github.com/nguyentuanphi1609/Project_CloudComputing/files/6383707/DynamoDB-da.chuy.n.d.i.pdf)
Phiên bản pdf.
