### ISSUE TITLE
Tìm hiểu về Python Django

### ISSUE THREAD

**Issue by nguyentuanphi1609** [nguyentuanphi1609/Project_CloudComputing#2]

**Comment by myle2000** [comment]
[Django.docx](https://github.com/nguyentuanphi1609/Project_CloudComputing/files/6377354/Django.docx)

**Comment by myle2000** [comment]
[Django-đã chuyển đổi.pdf](https://github.com/nguyentuanphi1609/Project_CloudComputing/files/6383714/Django-da.chuy.n.d.i.pdf)
Phiên bản pdf.
