### ISSUE TITLE
Thiết kế được một database sử dụng DynamoDB thực hiện đủ các thao tác thông qua AWS Cloud9

### ISSUE THREAD

**Issue by nguyentuanphi1609** [nguyentuanphi1609/Project_CloudComputing#4]

**Comment by myle2000** [comment]
[databaseByDynamoDB-đã chuyển đổi.pdf](https://github.com/nguyentuanphi1609/Project_CloudComputing/files/6383915/databaseByDynamoDB-da.chuy.n.d.i.pdf)
Phiên bản pdf.
