### ISSUE TITLE
Thiết kế được trang web đơn giản bằng django

### ISSUE THREAD

**Issue by nguyentuanphi1609** [nguyentuanphi1609/Project_CloudComputing#7]

**Comment by myle2000** [comment]
[WebDjango-đã chuyển đổi.pdf](https://github.com/nguyentuanphi1609/Project_CloudComputing/files/6383702/WebDjango-da.chuy.n.d.i.pdf)
Ảnh minh họa cho phần thực hiện(phiên bản pdf)
